<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>aspnet-Dalmatian-BBB373B5-EF3F-4DBB-B8AA-7152CEC275BF</UserSecretsId>
	<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <CodeAnalysisRuleSet>..\..\Rules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>


    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" PrivateAssets="all" />
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.114" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.12" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data\Dalmatian.Data.Models\Dalmatian.Data.Models.csproj" />
    <ProjectReference Include="..\..\Data\Dalmatian.Data\Dalmatian.Data.csproj" />
    <ProjectReference Include="..\..\Services\Dalmatian.Services.Data\Dalmatian.Services.Data.csproj" />
    <ProjectReference Include="..\..\Services\Dalmatian.Services.Mapping\Dalmatian.Services.Mapping.csproj" />
    <ProjectReference Include="..\..\Services\Dalmatian.Services.Messaging\Dalmatian.Services.Messaging.csproj" />
    <ProjectReference Include="..\..\Services\Dalmatian.Services\Dalmatian.Services.csproj" />
    <ProjectReference Include="..\Dalmatian.Web.Infrastructure\Dalmatian.Web.Infrastructure.csproj" />
    <ProjectReference Include="..\Dalmatian.Web.ViewModels\Dalmatian.Web.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Controllers\" />
  </ItemGroup>
</Project>
